---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

matrix:
  fast_finish: true

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
